name: Actions Build

# Run this workflow every time a new commit pushed or pulled to master repository
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  clang-format-linter:
    name: Clang Format Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        extensions: 'h,cpp'
        clangFormatVersion: 11

  c-cpp:
    name: C/C++ CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: configure
    #   run: ./configure
    - name: make
      run: make
    - name: make test
      run: ./test
